/**
 * 
 */
package tendril.codegen.field;

import static org.mockito.Mockito.verifyNoInteractions;

import java.util.Set;

import org.junit.jupiter.api.Assertions;
import org.mockito.Mock;

import tendril.dom.type.core.ClassType;
import test.AbstractUnitTest;

/**
 * Test case covering the shared/common needs for JValue tests
 */
public class AbstractJValueTest extends AbstractUnitTest {
    
    // Mocks to use for testing
    @Mock
    protected Set<ClassType> mockImports;

    /**
     * @see test.AbstractUnitTest#prepareTest()
     */
    @Override
    protected void prepareTest() {
        // Nothing to do
    }

    /**
     * Verify that the code generated by the {@link JValue} is correct
     * 
     * @param expectedCode {@link String} the code that should be generated
     * @param actualValue {@link JValue} which generates the code
     */
    protected void assertCode(String expectedCode, JValue<?> actualValue) {
        Assertions.assertEquals(expectedCode, actualValue.generate(mockImports));
        verifyMockImports();
    }
    
    /**
     * Verify that the expected interactions took place with the mockImports
     */
    protected void verifyMockImports() {
        verifyNoInteractions(mockImports);
    }
}
