package test.assertions;

import tendril.dom.classes.ImportElement;

/**
 * Assertions to help with custom Tendril classes
 */
public class TendrilAssert {
    
    /**
     * Assertion to verify that two {@link ImportElement} instances are the same
     * 
     * @param expected {@link ImportElement} that is expected
     * @param actual {@link ImportElement} that was actually generated by the code under test
     */
    public static void assertEquals(ImportElement expected, ImportElement actual) {
        assertImportData(expected.getPackageName(), expected.getClassName(), actual);
    }

    /**
     * Assertion to verify that the {@link ImportElement} is as expected
     * 
     * @param expectedPkg  {@link String} the expect package name of the import
     * @param expectedName {@link String} the expected class name of the import
     * @param actual       {@link ImportElement} to verify
     */
    public static void assertImportData(String expectedPkg, String expectedName, ImportElement actual) {
        TestHelper.assertEquals(expectedPkg, actual.getPackageName(), "ImportData package name mismatch");
        TestHelper.assertEquals(expectedName, actual.getClassName(), "ImportData class name mismatch");
    }
}
