name: Maven Central Publish

on:
  release:
    types: [created]

env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}      
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Maven Library build and publish
      run: ./gradlew publish --no-daemon
